### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by nafasebra** [DonyaOS/Donya#23]
My name is Nafiseh Ebrahimi and I have been working as a frontend developer for 6 month

**Comment by jbampton** [comment]
Hello @nafasebra you can say hello in the new team members issue and we will send you an invite to the team:

https://github.com/DonyaOS/Donya/issues/4

**Comment by MOGGSAS** [comment]
Hello I am @moggsas i want to do some configuration with a lenguage by my own creation, who wants to try to decrypt some text, and the most important part, how can i create a text and send it to you? im learning to program and to use thios plataform
thank you all

**Comment by BaseMax** [comment]
> how can I ... send it to you?

Welcome @moggsas 
You can mail me if you want. MaxBaseCode [.@.] gmail {.DOT.} (You can find my email address at my GitHub profile)
